Adding Infested Marines and Infested Bunkers (and a little more)
Ziktofel/Archipelago-SC2-data pull request #209
Opened 2024-07-23 21:01 UTC by EnvyDragon

Generator PR here: https://github.com/Ziktofel/Archipelago/pull/248

New items to unlock:
- Infested Marine, a timed-life unit (90s) buildable from the Infested Barracks.
- Infested Bunker, comes with 4 Infested Troopers, can uproot to move around and attack. While rooted, regenerates health and spawns new troopers every 30s.
- Sustained Cultivation Ventricles (Infested SCV): Increases InfSCV build charges to 3 starting, 5 max.
- Plagued Munitions (Infested infantry): Adds a damage over time effect to the weapons of Infested Marines, Infested Troopers, and Infestor Infested Terrans.
- Retinal Augmentation (Infested infantry): Adds +1 range to the weapons of Infested Marines/Troopers/Infestor Terrans.
- Calcified Armor (Infested Bunker): Adds +3 armor to the Infested Bunker.
- Regenerative Plating (Infested Bunker): Increases Infested Bunker regen rate while rooted.
- Engorged Bunkers (Infested Bunker): +2 cargo space and 20% reduced cooldown on trooper spawning for Infested Bunkers.

Supporting units (ie. not items to be found in the world, but either unlocked or produced by the above):
- Infested SCV, buildable from Hatchery/Lair/Hive on a charge system. Starts at 1 charge to limit arbitrary boost to economic power, with an upgrade that can increase it to the Stukov Co-op levels (3 starting charges, 5 max).
- Infested Trooper, a timed-life unit (30s) spawned automatically from the Infested Bunker. Almost entirely identical to the Infested Marine.
- Infested Barracks, stores 10 charges of Infested Marines. Can uproot/root to move around.
- Infested Cocoons, which InfSCVs and Infested Marines spawn from. 

Triggers:
- When Infested Bunkers are built, they are filled with Infested Troopers up to their cargo capacity.
- When Infested Bunkers fire their periodic "spawn" dummy behavior, a new Trooper is either added to their cargo or spawned outside, moving to a rally point if applicable.
- When either of the above triggers occur, the spawned troopers get a timed life behavior applied to them.

2024-07-24 19:31 UTC, Ziktofel commented
![Snímek obrazovky pořízený 2024-07-24 21-29-50](https://github.com/user-attachments/assets/dad6903a-be8c-4748-bb3a-8b18623015e2)
![Snímek obrazovky pořízený 2024-07-24 21-29-32](https://github.com/user-attachments/assets/22e04032-e1ca-4efb-bd88-e070be49557a)
Bug: Infested SCV gets the attack speed upgrade from normal SCV (Hostile Environment Adaptation) but not its HP or displayed icon

2024-07-24 19:32 UTC, Ziktofel commented
Normal SCVs autocast repairs. Infested don't
![Snímek obrazovky pořízený 2024-07-24 21-32-11](https://github.com/user-attachments/assets/fae42fea-5bd0-4602-81fb-54e36b8fa8bd)

2024-07-24 19:35 UTC, Ziktofel commented
Script Error:
![Snímek obrazovky pořízený 2024-07-24 21-35-14](https://github.com/user-attachments/assets/522c3c28-bc45-48ea-aaba-4e113cdac59f)

2024-07-24 19:46 UTC, Ziktofel commented
![Snímek obrazovky pořízený 2024-07-24 21-46-02](https://github.com/user-attachments/assets/a6ecbdf2-39a8-43b1-a53b-2bb172438583)
Missing Actor `AP_SIInfestedMarine_Land`

2024-07-24 19:48 UTC, Ziktofel commented
![Snímek obrazovky pořízený 2024-07-24 21-47-51](https://github.com/user-attachments/assets/d5843d5e-3334-440f-ad0d-81cd03bafe38)
Wild Mutation (Shield name/color needs to be copied from other Zerg units like lings)

2024-07-24 20:03 UTC, Ziktofel commented
![Snímek obrazovky pořízený 2024-07-24 22-02-29](https://github.com/user-attachments/assets/76a582e9-9422-4533-85b9-43799475213b)
![Snímek obrazovky pořízený 2024-07-24 22-02-18](https://github.com/user-attachments/assets/d834ff9e-1482-4a1b-a234-22bf3e13e028)
Add a requirement for Rooted for display (the same way as Tank use). Also do this for Regenerative Plating icon

2024-07-24 20:14 UTC, Ziktofel requested changes
Fix the bugs from above

2024-07-24 22:54 UTC, EnvyDragon commented
> Script Error: ![Snímek obrazovky pořízený 2024-07-24 21-35-14](https://private-user-images.githubusercontent.com/3447808/351853531-522c3c28-bc45-48ea-aaba-4e113cdac59f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NjE2NjEsIm5iZiI6MTcyMTg2MTM2MSwicGF0aCI6Ii8zNDQ3ODA4LzM1MTg1MzUzMS01MjJjM2MyOC1iYzQ1LTQ4ZWEtYWFiYS00ZTExM2NkYWM1OWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjRUMjI0OTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWYwYWFmMDU3NjY0ZjhjNzQwNTc3ZDkxYTdjNDY0ZjU4YzU5Nzc5MTQ0ZmRjODYwOGExMDA3NTI2OGYyOGU3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8EOWy9I07OZ4vIF2HdgtXX-K9H3cTCj30_pfFmy_A3Q) Triggers when Infested Bunker completes `Spawn Infested Trooper` and rally point is not set

This error is harmless and is accounted for in the triggers. Unfortunately the sc2 editor doesn't appear to have a try/catch method, so if I use the only function in existence that can get the target point of a rally ability, it throws an error if there's no rally point. I'll take a second look, but the script error doesn't show up in regular gameplay and the trigger is designed to accommodate a missing point even if the editor finds it upsetting.

2024-07-24 22:56 UTC, EnvyDragon commented
> Add a requirement for Rooted for display (the same way as Tank use). Also do this for Regenerative Plating icon

What you're seeing is the vanilla behavior. The icon is present-but-disabled when uprooted so it's clearer to players that it won't spawn if it's mobile. I can put the same visual effect on Regenerative Plating though, if it helps.

2024-07-24 23:14 UTC, Ziktofel commented
> > Script Error: ![Snímek obrazovky pořízený 2024-07-24 21-35-14](https://private-user-images.githubusercontent.com/3447808/351853531-522c3c28-bc45-48ea-aaba-4e113cdac59f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NjE2NjEsIm5iZiI6MTcyMTg2MTM2MSwicGF0aCI6Ii8zNDQ3ODA4LzM1MTg1MzUzMS01MjJjM2MyOC1iYzQ1LTQ4ZWEtYWFiYS00ZTExM2NkYWM1OWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjRUMjI0OTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWYwYWFmMDU3NjY0ZjhjNzQwNTc3ZDkxYTdjNDY0ZjU4YzU5Nzc5MTQ0ZmRjODYwOGExMDA3NTI2OGYyOGU3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8EOWy9I07OZ4vIF2HdgtXX-K9H3cTCj30_pfFmy_A3Q) Triggers when Infested Bunker completes `Spawn Infested Trooper` and rally point is not set
> 
> This error is harmless and is accounted for in the triggers. Unfortunately the sc2 editor doesn't appear to have a try/catch method, so if I use the only function in existence that can get the target point of a rally ability, it throws an error if there's no rally point. I'll take a second look, but the script error doesn't show up in regular gameplay and the trigger is designed to accommodate a missing point even if the editor finds it upsetting.

Add a check if the point exists and if not, use Skip Remaining Actions

2024-07-24 23:16 UTC, Ziktofel commented
> > Add a requirement for Rooted for display (the same way as Tank use). Also do this for Regenerative Plating icon
> 
> What you're seeing is the vanilla behavior. The icon is present-but-disabled when uprooted so it's clearer to players that it won't spawn if it's mobile. I can put the same visual effect on Regenerative Plating though, if it helps.

Use the same visual effect + like tanks do, use the requirement that tells the player that the infested bunker needs to be rooted. It's used for Tanks/Liberators/Vikings where a trait works only in one mode

2024-07-24 23:49 UTC, EnvyDragon commented
> > > Add a requirement for Rooted for display (the same way as Tank use). Also do this for Regenerative Plating icon
> > 
> > 
> > What you're seeing is the vanilla behavior. The icon is present-but-disabled when uprooted so it's clearer to players that it won't spawn if it's mobile. I can put the same visual effect on Regenerative Plating though, if it helps.
> 
> Use the same visual effect + like tanks do, use the requirement that tells the player that the infested bunker needs to be rooted. It's used for Tanks/Liberators/Vikings where a trait works only in one mode

Not sure what you mean or what you're suggesting, so I just did this:
![image](https://github.com/user-attachments/assets/d0adf40c-96c7-4512-965d-53642f9582ff)

2024-07-24 23:50 UTC, EnvyDragon commented
> > > Script Error: ![Snímek obrazovky pořízený 2024-07-24 21-35-14](https://private-user-images.githubusercontent.com/3447808/351853531-522c3c28-bc45-48ea-aaba-4e113cdac59f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NjE2NjEsIm5iZiI6MTcyMTg2MTM2MSwicGF0aCI6Ii8zNDQ3ODA4LzM1MTg1MzUzMS01MjJjM2MyOC1iYzQ1LTQ4ZWEtYWFiYS00ZTExM2NkYWM1OWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjRUMjI0OTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWYwYWFmMDU3NjY0ZjhjNzQwNTc3ZDkxYTdjNDY0ZjU4YzU5Nzc5MTQ0ZmRjODYwOGExMDA3NTI2OGYyOGU3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8EOWy9I07OZ4vIF2HdgtXX-K9H3cTCj30_pfFmy_A3Q) Triggers when Infested Bunker completes `Spawn Infested Trooper` and rally point is not set
> > 
> > 
> > This error is harmless and is accounted for in the triggers. Unfortunately the sc2 editor doesn't appear to have a try/catch method, so if I use the only function in existence that can get the target point of a rally ability, it throws an error if there's no rally point. I'll take a second look, but the script error doesn't show up in regular gameplay and the trigger is designed to accommodate a missing point even if the editor finds it upsetting.
> 
> Add a check if the point exists and if not, use Skip Remaining Actions

Skip Remaining Actions isn't an option because it needs to do a bunch of other actions, like spawning the actual unit. I found a workaround though, the error warning is now gone.

2024-07-25 16:54 UTC, Ziktofel commented
> > > > Add a requirement for Rooted for display (the same way as Tank use). Also do this for Regenerative Plating icon
> > > 
> > > 
> > > What you're seeing is the vanilla behavior. The icon is present-but-disabled when uprooted so it's clearer to players that it won't spawn if it's mobile. I can put the same visual effect on Regenerative Plating though, if it helps.
> > 
> > 
> > Use the same visual effect + like tanks do, use the requirement that tells the player that the infested bunker needs to be rooted. It's used for Tanks/Liberators/Vikings where a trait works only in one mode
> 
> Not sure what you mean or what you're suggesting, so I just did this: ![image](https://private-user-images.githubusercontent.com/138727357/351911100-d0adf40c-96c7-4512-965d-53642f9582ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MjY0MzIsIm5iZiI6MTcyMTkyNjEzMiwicGF0aCI6Ii8xMzg3MjczNTcvMzUxOTExMTAwLWQwYWRmNDBjLTk2YzctNDUxMi05NjVkLTUzNjQyZjk1ODJmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxNjQ4NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmEwNmRjNmYxOGJkZWRhNTVhOWMxYTg5OTg4MTAwZWY1ZTUyYzcyYzM4MDUzNmY5OTA4OTVmNWM5YjBlOTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HDus2XcuWSPAjbBqXB2t7H3jNXLMgmUYWQVRz7hzjsI)

![Snímek obrazovky pořízený 2024-07-25 18-52-35](https://github.com/user-attachments/assets/5123ab6c-eff9-45af-aeee-1754466b6b19)
Add this (it's a requirement that leads to an upgrade that's never researched). All transformers in AP use this

2024-07-25 17:00 UTC, Ziktofel commented
[
![Snímek obrazovky pořízený 2024-07-25 18-57-00](https://github.com/user-attachments/assets/3e3e7de5-64fd-4774-8024-c3e7412caf9c)
![Snímek obrazovky pořízený 2024-07-25 18-56-02](https://github.com/user-attachments/assets/7447b28f-405c-41f6-a50b-cbeacfced1b8)
](url)
Infested SCVs are affected by Terran Advanced Construction upgrade but the player isn't notified about that

2024-07-25 17:04 UTC, Ziktofel requested changes

2024-07-25 17:04 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +            <LayoutButtons Face="Repair" Type="AbilCmd" AbilCmd="Repair,Execute" Row="2" Column="2"/>
AP_Repair

2024-07-25 17:04 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +            <LayoutButtons Face="ReturnCargo" Type="AbilCmd" AbilCmd="SCVHarvest,Return" Row="1" Column="1"/>
AP_SCVHarvest

2024-07-25 17:13 UTC, EnvyDragon commented
> ![Snímek obrazovky pořízený 2024-07-25 18-52-35](https://private-user-images.githubusercontent.com/3447808/352222575-5123ab6c-eff9-45af-aeee-1754466b6b19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MjY4ODEsIm5iZiI6MTcyMTkyNjU4MSwicGF0aCI6Ii8zNDQ3ODA4LzM1MjIyMjU3NS01MTIzYWI2Yy1lZmY5LTQ1YWYtYWVlZS0xNzU0NDY2YjZiMTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMTY1NjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWFhMTc2ZWNhODg2ZWE0OWVmYWEwM2JkNzFhNTI1YzFhNjFlZDgzMmE2MWFlZDdiYjM0OTg1NTljZDgwMTBiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MPuvJu5ABDnIoKc-aabOvlnTXei_fplam3ph87W8sIg) Add this (it's a requirement that leads to an upgrade that's never researched). All transformers in AP use this

![image](https://github.com/user-attachments/assets/2fb3c0e6-b1fe-44b2-9283-a29cc8e95453)
Added! Will add the SCV upgrades then commit.

2024-07-25 17:18 UTC, Ziktofel commented
Also if your Infested Barracks is uprooted, you can no longer build infested Bunkers (normally lifted off buildings do count for tech requirements)
![Snímek obrazovky pořízený 2024-07-25 19-17-01](https://github.com/user-attachments/assets/739183ea-9b9e-4c8b-8fdd-18e1c0fb8772)

2024-07-25 17:48 UTC, EnvyDragon commented
![image](https://github.com/user-attachments/assets/8ac2e7be-8d94-4a85-94cd-bda2084b81a9)
Applied SCV upgrades to infested SCVs

2024-07-25 17:49 UTC, EnvyDragon commented
Uprooted Barracks now uses the same tech alias as the rooted version (pictured is the only infested barracks on the map)
![image](https://github.com/user-attachments/assets/ca3884a2-9746-401d-a44b-639153d577ca)

2024-07-26 16:21 UTC, merged