Nydus Worm/Omega Worm Structures with Respective Upgrades
Ziktofel/Archipelago-SC2-data pull request #227
Opened 2024-07-30 21:11 UTC by SirChuckOfTheChuckles

(Opening a different pull request since I messed up and couldn't update the old one properly)
Adds the Nydus Worm and Omega Worm units to Archipelago, along with respective upgrades to them:

- The Nydus Worm works extremely similar to it's version in multiplayer; 100 mineral, 100 gas cost, 20 second "build" time, and transport Zerg units throughout the Nydus Transport system. 30 second cooldown to create
- The Omega Worm cannot transport units and costs ~~100~~ 50 more minerals **and 25 less gas,** but spreads creep and has the ability to create creep tumors. It has greatly increased health, and allows drones to drop-off minerals/gas to the Worms like they are a hatchery. 180 second cooldown to create

Upgrades:
Jormungandr Strain - Removes emerge time for Nydus and Omega Worms, and allows them to be salvaged, returning the cost spent on them.
Ravenous Appetite - Allows Nydus Worms to unload and load units nearly instantly.
Subterranean Scales - Increases Nydus and Omega Worms maximum health by 250 and armor by 1.
Resource Efficiency - Decreases the cost of Nydus Worms and Omega Worms by ~~100~~  **75** minerals and ~~100~~ **75** gas
Ouroboros Strain - Allows Omega Worms to train a limited assortment of combat units (Zerglings, Roaches, Hydralisks, and Aberrations) at a reduced time and cost (roughly 10% cost).

Fixed many of the issues brought up during last pull request:
- Most instances of Nydus Canal has been renamed to Nydus Worm, to avoid confusion.
- Unnecessary lines no longer deleted

Nydus Salvage Example:

https://github.com/user-attachments/assets/2bd84856-49e4-4bb5-81be-16fb1cff95b8

Ouroboros Unit Creation Example:

https://github.com/user-attachments/assets/a84f88ce-d6a5-4461-8eb4-e69399894280

Ravenous Appetite Example:

https://github.com/user-attachments/assets/5d39efca-3c21-4e6a-8932-d1fd8615237e

Omega Worm Base Function Example:

https://github.com/user-attachments/assets/8261a1a7-5c80-4bac-84cd-f902d7d27df5

2024-08-01 19:41 UTC, SirChuckOfTheChuckles commented
Note: made slight balance changes:
- Reduced Omega Worm cost by 25% (now 150 minerals and 75 gas)
- Reduced Resource Efficiency reduction from 100 minerals and 100 gas to 75 minerals and 75 gas.
- Reduced Omega Worm cooldown from 3 minutes to 1 minute.

Goal was to make omega worms not feel so pricy without resource efficiency. Nydus worms costing 25 minerals and 25 gas should hopefully not be an issue.
Long cooldown was meant to act as a balancing factor for an earlier design of the omega worm, but final design results in longer cooldown no longer being needed.

2024-08-02 14:13 UTC, Ziktofel requested changes

2024-08-02 14:13 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ActorData.xml
> +        <On Terms="Behavior.AP_SalvageNydus.Off" Send="Destroy"/>
Is it needed to patch vanilla stuff (if so, add `<!-- Override -->` comment, otherwise create a new Actor, dedicated to AP unit

2024-08-02 14:13 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/RequirementNodeData.xml
> +    </CRequirementCountUpgrade>
All created objects, inlcuding requirements start with the `AP_` prefix

2024-08-02 14:13 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +            <LayoutButtons Face="AP_BirthAberration" Type="AbilCmd" AbilCmd="AP_OmegaTrain,Train11" Row="2" Column="4"/>
You're missing the button for cancel (like Barracks has). I'd move all train buttons to the first row (that's currently empty) thus creating a room at bottom right for cancel
![Snímek obrazovky pořízený 2024-08-02 16-09-02](https://github.com/user-attachments/assets/c74a9664-05ae-4cb7-871c-128786f39fbb)
![Snímek obrazovky pořízený 2024-08-02 16-08-33](https://github.com/user-attachments/assets/7408338b-bcf4-476f-98af-ce5c7d8a0a7a)

2024-08-02 14:13 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +            <LayoutButtons Face="AP_BirthAberration" Type="AbilCmd" AbilCmd="AP_OmegaTrain,Train11" Row="2" Column="4"/>
Also you can queue 8 lings but the 8th is hidden as the bottom row of queues can display only up to 6 elements

2024-08-03 18:46 UTC, SirChuckOfTheChuckles commented
I made changes to all of the issues that Ziktofel brought up, and making sure Omega Worm still worked as before with the changes requesting (queue going down to 7 so can see bottom 6 in it, command card rearrange with a cancel train command, creep now produced when malignant creep researched).

2024-08-03 18:59 UTC, merged