Add infested units
Ziktofel/Archipelago-SC2-data pull request #273
Opened 2024-09-01 22:21 UTC by itsjustbones

Adds the following

Renames old infested merc siege tank and banshees to infested siege breakers and dusk wings
adds coop stukov's infested factory, starport, and their tech labs (barracks not included, since there isn't any use for it)
adds coop stukov's infested siege tank, diamondback, liberator, and banshee.  Also adds volatile infested, which are used by the siege tank.
Adds the following upgrades
"Progressive Automated Mitosis (Infested Siege Tank)" - 2 levels, 1st is ammo every 30 seconds, 2nd is every 10 seconds (2nd level based on stukov prestige)
"Acidic Enzymes (Infested Siege Tank)" - +15 damage to armored units
"Deep Tunnel (Infested Siege Tank)" - deep tunnel to visible creep
"Frightful Fleshwelder (Zerg)" - 30% Resource efficiency for infested mech units, based on stukov prestige.  I thought about splitting it up into 4 upgrades, but didn't really want to without feedback
"Saturated Cultures (Infested Diamondback)" - reduce snare cooldown from 45 to 30 seconds
"Caustic Mucus (Infested Diamondback)" - adds slowing and damaging trail behind diamondback
"Braced Exoskeleton (Infested Banshee)" - +100 life
"Rapid Hibernation (Infested Banshee)" - allows burrowing, which gives increased life and energy regen
"Cloud Dispersal (Infested Liberator)" - changes the attack to be melee and gives 85% dr when active
"Viral Contamination (Infested Liberator)" - doubles primary attack target damage

I didn't apply other upgrades to the mech units.  Based on some leftover code in the stukov units, I decided to add some of the baneling upgrades to the volatile infected.  these might be too powerful, but they are cool, people recommended using banelings anyway, which would have caused this anyway (even worse, actually)
rupture  - 50% greater aoe size
corrosive bile - double direct target damage
healing explosion - heals 40 to friendlies in aoe

I didn't add screenshots here, since it's a lot of stuff and I didn't really want to make them if it's not needed, but let me know if you want them.

2024-09-04 14:10 UTC, Ziktofel commented
Bug: Missing Banshee cloak/decloak sound

2024-09-04 14:10 UTC, Ziktofel commented
![Uploading Snímek obrazovky pořízený 2024-09-04 16-07-15.png…]()

2024-09-04 14:46 UTC, Ziktofel commented
![Snímek obrazovky pořízený 2024-09-04 16-45-29](https://github.com/user-attachments/assets/6241a8cc-5ef0-469e-b770-2734e0144e34)
No hotkey for Enable/Disable structure attack

2024-09-04 14:46 UTC, Ziktofel commented
I'd consider Infertor's infested Terrans being able to be used as ammo for tanks

2024-09-04 14:51 UTC, Ziktofel commented
Tank's Volatile Burst could enjoy a tooltip telling the player what it exactly does

2024-09-04 14:57 UTC, Ziktofel commented
Cloud Dispersal decreases attack range. There should remain a way to attack in the standard range after getting the item

2024-09-04 15:02 UTC, Ziktofel commented
![Snímek obrazovky pořízený 2024-09-04 17-01-32](https://github.com/user-attachments/assets/b58c51ac-483c-42b4-9f84-ca3543c1d30c)
Root/uproot tooltips need to be updated - Tank can attack in both modes but can launch volatile infesteds while rooted

2024-09-07 23:47 UTC, itsjustbones commented
Should have fixed or implemented everything mentioned.  not 100% I fixed the siege tank issue though, I'm not sure what that actor error overlay is, but I'd like to know for the future.

2024-09-09 19:08 UTC, Ziktofel requested changes

2024-09-09 19:38 UTC, itsjustbones commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ActorData.xml
> +        <On Terms="ActorCreation" Send="Create StukovInfestedLiberator_AttackLaunchSound"/>
fixed

2024-09-09 19:56 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ActorData.xml
> +        <ImpactMap index="None" Model="AP_Stukov_Infested_Liberator_Missile_Impact" Sound="AP_StukovInfestedLiberator_AttackImpact"/>
Missing this sound:
```xml
    <CSound id="StukovInfestedLiberator_AttackImpact" parent="Combat">
        <EditorCategories value="Race:Terran"/>
        <AssetArray File="Assets\Sounds\StukovInfestedLiberator_AttackImpact_01.wav" FacialGroup=""/>
        <AssetArray File="Assets\Sounds\StukovInfestedLiberator_AttackImpact_02.wav" FacialGroup=""/>
        <AssetArray File="Assets\Sounds\StukovInfestedLiberator_AttackImpact_03.wav" FacialGroup=""/>
        <AssetArray File="Assets\Sounds\StukovInfestedLiberator_AttackImpact_04.wav" FacialGroup=""/>
        <DupeDestroyCount value="3"/>
        <DupeMaximumMethod value="Replace"/>
        <DupeMuteCount value="5"/>
        <Pitch value="1.000000,2.000000"/>
        <Volume value="-9.000000,-7.000000"/>
    </CSound>
```

2024-09-09 20:13 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ValidatorData.xml
> +    <CValidatorUnitType id="AP_IsAP_InfestedTerranBurrowed">
Typo: `AP_IsAP_InfestorTerranBurrowed`
![Snímek obrazovky pořízený 2024-09-09 22-13-02](https://github.com/user-attachments/assets/a3b75d02-4744-433a-ad0a-87180faeded1)

2024-09-09 20:19 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ActorData.xml
> +        <On Terms="Behavior.AP_StukovInfestedSiegeTankAmmo.On; ValidateUnitType IsSISiegeTankSieged" Send="Create"/>
![Snímek obrazovky pořízený 2024-09-09 22-17-45](https://github.com/user-attachments/assets/236e0515-3341-42e8-9b77-d20a6b1d4616)
Missing `AP_` Prefix in Validator

2024-09-09 20:37 UTC, merged