sc2: Added Pygalisks
Ziktofel/Archipelago-SC2-data pull request #321
Opened 2024-11-26 05:20 UTC by MatthewMarinets

Adding pygalisks.

Currently adding them on the Predator Nest, but I'm not completely happy with it, because the whole point is they're supposed to be accessible. Gave them a 60s cooldown and uncapped count by default, though that means merc upgrades can't realistically affect them. Currently 6 for 300 minerals (50 minerals per).

I buffed their stats slightly from Piercing the Shroud:
* Damage +4 (4->8)
* Life +25 (50->75)
* Armor +1 (2->3)

Also gave them burrow and a chibified version of the Ultra's old Ram attack, at about half the attack speed of their vs units attack but 25 damage per attack.

I like the identity of a small, cheap, but durable army that has low DPS. They still melt vs anything that does more than zergling damage per attack lol.

## TODO
- [ ] Proper Unlock Trigger
- [ ] Some upgrades
  - [ ] Ducal Blades (splash damage)
  - [ ] Stim (they are a dominion experiment)
  - [ ] Combat Carapace (more health, mashup of Combat Shield+Organic Carapace)
  - [ ] Rapid regeneration / some kind of regen ability. Maybe on burrow?

2024-11-26 06:30 UTC, MatthewMarinets commented
![image](https://github.com/user-attachments/assets/6e6c8e87-de1f-4f5d-a7de-f0dca008c783)
![image](https://github.com/user-attachments/assets/0840bfd1-6966-464f-8a5e-1e7f906b2fa3)
![image](https://github.com/user-attachments/assets/1db23e65-1b3a-4f41-b16d-9e04c7768386)

Changed around the wireframes and buttons a bit so you can more easily tell them apart from ultras in the command-card. Not fully happy with the button, it's kind of the wrong colour, but all the other ultralisk buttons are even more off (and the baseline one looks huge)

2024-11-28 07:41 UTC, MatthewMarinets commented
Tested with `/send` commands, everything unlocked properly (even the Predator nest on getting Pygalisks).
![image](https://github.com/user-attachments/assets/76799f9b-bebe-4b5f-ba66-63ac1b5ea56e)

I'm not fully happy with them on the predator nest; it would be nice to see a different way to build them, but it will do for now until we agree on a better solution.

2024-11-28 16:47 UTC, Ziktofel requested changes

2024-11-28 16:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <CostResource index="Minerals" value="50"/>
![Snímek obrazovky pořízený 2024-11-28 17-46-10](https://github.com/user-attachments/assets/1c73e395-7b03-461d-a17b-6ee602e32cda)
Should match the unburrowed form

2024-11-28 20:35 UTC, Ziktofel requested changes

2024-11-28 20:45 UTC, Ziktofel commented
![Snímek obrazovky pořízený 2024-11-28 21-44-19](https://github.com/user-attachments/assets/cc954050-0ecf-402b-b2b5-647abff8ceea)
No HP upgrade, no upgrade icons

2024-11-28 20:52 UTC, merged