SC2: Add Roach Mercenaries
Ziktofel/Archipelago-SC2-data pull request #333
Opened 2024-12-04 19:09 UTC by Snarkie

## What is this fixing or adding?

Adds a Roach Mercenary item. Working name: Thornshells.
Stronger versions of regular Roaches, that can attack air.

## How was this tested?

Generated a local campaign, added item with console commands

[Client PR](https://github.com/Ziktofel/Archipelago/pull/363)

2024-12-05 10:52 UTC, Ziktofel commented
![Snímek obrazovky pořízený 2024-12-05 11-51-52](https://github.com/user-attachments/assets/0b772b99-26ce-4e7f-9c0b-09c0041d6479)
![Snímek obrazovky pořízený 2024-12-05 11-51-44](https://github.com/user-attachments/assets/23ac7278-74a4-4d17-b25e-673ce34b2789)
Check Malignant Creep bonus

2024-12-05 11:06 UTC, Ziktofel requested changes
I'll check training after the Pygalisk related change gets merged

2024-12-05 11:39 UTC, Snarkie commented
> Check Malignant Creep bonus
fixed

2024-12-05 11:39 UTC, Snarkie commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UpgradeData.xml
> +        <EffectArray Reference="Effect,AP_RoachVileAcidSalivaU,Amount" Value="3"/>
Correct, that was unintended. Fixed.

2024-12-05 13:28 UTC, Snarkie commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ActorData.xml
> +        <On index="6" Terms="Effect.AP_MercRoachCorpserAcidSalivaLM.Start; At Caster" Send="Create"/>
All event indexes replaced with Remove + On

2024-12-06 12:20 UTC, Ziktofel commented
Fixed the attack missile spawning point

2024-12-06 13:37 UTC, Snarkie commented
> Fixed the attack missile spawning point

Funny, my initial setup had something very similar (I went with .7 offset)

Ultimately decided against it because regular roach missile also awkwardy starts more towards the center of the unit and I thought I'd keep it consistent.

2024-12-06 13:57 UTC, Ziktofel requested changes

2024-12-06 16:07 UTC, Snarkie commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/WeaponData.xml
> +        <MinimumRange value="0.6"/>
fixed

2024-12-06 16:24 UTC, Snarkie commented
Tested again in local campaign. 

- Training works
- air attack close range works
- actors seem to work
- all items work (including strain combinations)
- malignant creep works
- mercenary cooldown upgrades work

2024-12-07 11:41 UTC, merged