Update unit selection priorities
Ziktofel/Archipelago-SC2-data pull request #76
Opened 2024-01-23 23:18 UTC by FoxOfWar

Changes to subgroup selection, in order to have the units more used higher and to remove oddities. Heroes->casters->damage abilties->utility->blink->form changes->rest.

2024-01-23 23:29 UTC, MatthewMarinets commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="30"/>
Note: SentryBase

2024-01-23 23:30 UTC, MatthewMarinets commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="16"/>
Note: `AP_Marine`

2024-01-23 23:31 UTC, MatthewMarinets commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="5"/>
Note: `AP_Medic`

2024-01-23 23:32 UTC, MatthewMarinets commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Note: `AP_Firebat`

2024-01-23 23:32 UTC, MatthewMarinets commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Note: `AP_Marauder`

2024-01-23 23:33 UTC, MatthewMarinets commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="20"/>
Note: `AP_Reaper`

2024-01-23 23:33 UTC, MatthewMarinets commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="17"/>
Note: `AP_Hellion`

2024-01-23 23:33 UTC, MatthewMarinets commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="16"/>
Note: `AP_Vulture`

2024-01-23 23:33 UTC, MatthewMarinets commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Note: `AP_Goliath`

2024-01-25 18:47 UTC, Ziktofel requested changes
Surely, the units that never have any active ability should always have the lowest priority, then autocasts-only, then Medic/Medivac/Burrowers only. Then units with actives

From high tier - Heroes, then spellcasters

Also note that burrowed units usually can't do anything else than unburrow

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="18"/>
Brynhild Assault - should be same as Viking Assault

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="19"/>
Cyclone - one autocast ability - higher than Goliaths, lower than Marine (base stim not auto cast)?

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="16"/>
War Pig - Alias to Marine

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Devil Dog, Alias to Firebat

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Hammer Security, alias to Marauder

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Spartan Company, alias to Goliath

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="17"/>
Siege Breaker - alias to Tank

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="17"/>
Siege Breaker - Sieged - alias to Tank

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="18"/>
Hell's Anger Assault - alias to Viking Assault

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="18"/>
Hel's Angel Fighter - Alias to Viking Fighter

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="30"/>
Dusk Wing, Alias to Banshee

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="40"/>
Jackson's Revenge - alias to BC

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="41"/>
Leviathan (Summon) - spellcaster

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Dragoon - No actives (should have the same priority of Golaith/Diamondback)

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="98"/>
Kerrigan - Hero - should be on top

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="98"/>
Kerrigan - Burrowed

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="98"/>
Kerrigan alt unit, unused IIRC

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="20"/>
Infested Terran - only Burrow

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="20"/>
Infested Terran - Burrowed

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Aberration - only burrow. All burrow-only should have the same priority (but still lower than Marines/Wraiths)

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Aberration - Burrowed

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="17"/>
Impaler - burrow only - but this and Lurker should be above Marines/Wraiths (but under Banshees) due to how vital Burrow is for them

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="17"/>
Impaler Burrowed

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="17"/>
Lurker, See Impaler's note

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="17"/>
Lurker

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="17"/>
Hellbat - should be same as Hellion

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="45"/>
Infestor - Spellcaster

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="45"/>
Infestor - Burrowed

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Carrier - one autocast (should be below Marines and Medics)

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Carrier (Aiur) - see higher

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="19"/>
Phoenix - one autocast - maybe 1 over Carrier

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="19"/>
Mirage - see Phoenix

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Mutalisk - has morphs - between burrowers and cloakers

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="21"/>
Corruptor - Lesser Spellcaster

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="8"/>
Scourge - only one toggle (should be just above Goliaths)

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Immortal (Hardened Shield) - no actives - should be as Goliath

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Immortal (Aiur) - one autocast

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="40"/>
Annihilator - one spell - should be just below Thor

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Vanguard - no actives (should be Goliath tier)

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Colossus (Purifier) - should be the same as base colossus

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Wrathwalker - no actives - Goliath tier

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Archon - conditionally a spellcaster

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="25"/>
Basic DT - Archon Merge only

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="25"/>
Avenger - Blink only as upgrade (one point behind Stalker?)

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="25"/>
DT - Autocast, Archon merge and Blink on upgrade - should be higher than Avenger

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="25"/>
Blood Hunter - similar traits like DT but doesn't have Archon Merge (1 point below DT?)
Therefore: DT(Shakuras) > Blood Hunter > Avenger
Also: Stalker > Avenger

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="14"/>
Baneling - Burrow + Toggle (1 point over burrow only [Abberation])

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="14"/>
Baneling burrowed

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="13"/>
Baneling - Splitterling - small

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="13"/>
Baneling - Splitterling - small - burrowed

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="45"/>
Arbiter (spellcaster) - maybe should be less priority than other spellcasters

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="45"/>
Oracle - Spellcaster

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="40"/>
Disruptor - Spellcaster

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="40"/>
Disruptor - Nova

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="23"/>
Adept - one active, should be about blinkers/cloakers

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="22"/>
Adept shade

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="30"/>
Havoc - spellcaster, maybe should be same as Arbiter as both of them rely on their passives

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="19"/>
Swarm Queen - lesser spellcaster

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="19"/>
Swarm Queen - burrowed

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="4"/>
SCV - worker - should be just over Goliaths

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="40"/>
Ravager - lesser spellcaster (should be about BC or less)

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="40"/>
Ravager (Burrowed)

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="17"/>
Swarm Host - Burrow, autocast and toggle

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="17"/>
Swarm Host (Burrowed)

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="17"/>
Swarm Host (Rooted)

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="25"/>
Stalker - Blink

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="25"/>
Instigator

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="25"/>
Stalker (Shakuras)

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Scout - no actives (should be at Goliath tier)

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="25"/>
Slayer - should be same as Stalker

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Reaver- autocasts only

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="5"/>
Supplicant - no actives - should be at Goliath tier

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="30"/>
Energizer in Pylon Mode

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="45"/>
Brood Queen - Spellcaster

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Ultralisk - autocast and Burrow

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Ultralisk (Burrowed)

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Void Ray - No actives - should be as Goliath

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Destroyer - No Actives - should be as Goliath

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="45"/>
Viper - Spellcaster

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="40"/>
Tempest - one spell - should be lower than BC

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Devourer - no actives (should be like Goliath)

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="45"/>
Defiler - Spellcaster

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="45"/>
Defiler - Burrowed

2024-01-25 18:47 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="15"/>
Warhound - one autocast

2024-01-27 10:37 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="6"/>
Note: Medivac

2024-01-27 10:37 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="7"/>
Note: Widow Mine

2024-01-27 10:38 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="7"/>
Note: Widow Mine (Burrowed)

2024-01-27 10:38 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="6"/>
Note: HERC (has autocast)

2024-01-27 10:39 UTC, Ziktofel commented on Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
> +        <SubgroupPriority value="8"/>
Note: Hydralisk

2024-01-29 17:20 UTC, Magnemania commented
Wouldn't it be appropriate for MULE to be lower priority than SCV?  They can't build, and drag selecting will usually result in both MULEs and SCVs in the same group.

2024-01-29 17:22 UTC, MatthewMarinets commented
`AP_HoloDecoy` has `<SelectAlias value="AP_NovaHero"/>`, so I think it should match `AP_NovaHero` (or at least, I'm not sure the selection priority will affect anything if you change it.)

2024-01-29 17:24 UTC, MatthewMarinets commented
> Wouldn't it be appropriate for MULE to be lower priority than SCV? They can't build, and drag selecting a mineral line will usually result in both MULEs and SCVs in the same group.

I notice in liberty.sc2mod, SCVs have subgroup priority 6 and MULEs have 5, so this would match vanilla behaviour

2024-01-29 19:51 UTC, merged